### PR TITLE
add staking parametric contract in deploy script

### PR DESCRIPTION
**Pull request by Axel-CH**
Add oracleUseCaseSpec in deployment script
Add an IT contract for parametric staking

### CODE REVIEW

**Review by wilhempujar — COMMENTED** [review]
Why not simply changing `serviceMetadata` to `any` in `types.js`, and appending the oracle specs in the scripts?

**Comment by Axel-CH** [comment]
The goal is not to have too many "any" and limit the scope of the ones that we are forced to use

**Comment by Axel-CH** [comment]
Or I can add a "oracleUseCaseSpec" field of type any  in service metadata

**Comment by wilhempujar** [comment]
> Or I can add a "oracleUseCaseSpec" field of type any in service metadata

serviceMetadata is pushed to IPFS, so that's the easiest fix.

I don't think we can add oracleUseCaseSpec here without modifying how it's handled in subtasks.

**Review by wilhempujar — COMMENTED** [review]
Got to delete `oracleUseCaseSpec: {},`

**Review by wilhempujar — APPROVED** [review]
LGTM and tested without issues.

**Pull request merged**
